[build]
  functions = "functions"
# Set CORS headers to allow requests from specific origins
[[headers]]
  # Enable CORS for all paths (/*)
  for = "/*"
    [headers.values]
    Referrer-Policy = "no-referrer"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"
